language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 8
  - 7
  - 6
  - 4

after_success:
  - yarn run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
