language: node_js

cache: yarn

install:
  - yarn
  - yarn global add codecov

notifications:
  email: false

node_js:
  - 8
  - 7
  - 6
  - 10

after_success:
  - yarn run semantic-release
  - codecov

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
